import React from 'react';

const ApiResponseSchema = () => {
  return (
    <div className="api-section">
      <div className="api-section-body">
        <h3 style={{ fontSize: '14px', textTransform: 'uppercase', letterSpacing: '0.1em', color: 'var(--text-dim)', marginBottom: '16px' }}>Response Schema</h3>
        <div className="api-code">
          <pre style={{ margin: 0 }}><code className="api-url">
{`{
  "id": "gen-123",
  "model": "llama-3-8b",
  "choices": [
    {
      "text": "The response generated by the model...",
      "index": 0,
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 5,
    "completion_tokens": 12,
    "total_tokens": 17
  }
}`}
          </code></pre>
        </div>
      </div>
    </div>
  );
};

export default ApiResponseSchema;
